name: Check Package.json Version Bump

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check-version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Check for version bump
        run: |
          # If we're on a PR, diff against the PR base
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BASE_REF="${{ github.event.pull_request.base.sha }}"
            HEAD_REF="${{ github.sha }}"
            echo "Comparing PR changes from $BASE_REF to $HEAD_REF"
          else
            # If we're on a push to main, diff against the previous commit
            BASE_REF="${{ github.event.before }}"
            HEAD_REF="${{ github.sha }}"
            echo "Comparing push changes from $BASE_REF to $HEAD_REF"
          fi

          # Extract the current package.json version
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "Current version: $CURRENT_VERSION"

          # Check if package.json was modified
          if git diff --name-only $BASE_REF $HEAD_REF | grep -q "package.json"; then
            # Get the package.json from the base ref
            git show $BASE_REF:package.json > package.json.base
            
            # Extract the base version
            BASE_VERSION=$(node -p "require('./package.json.base').version")
            echo "Base version: $BASE_VERSION"
            
            # Compare versions using semver
            if node -e "process.exit(require('semver').gt('$CURRENT_VERSION', '$BASE_VERSION') ? 0 : 1)"; then
              echo "✅ Version bump detected: $BASE_VERSION -> $CURRENT_VERSION"
              exit 0
            else
              echo "❌ No version bump detected! Please update the version in package.json"
              exit 1
            fi
          else
            echo "⚠️ package.json not modified in this PR/commit."
            echo "❌ Please update the version in package.json"
            exit 1
          fi
