name: Codecheck

on:
  pull_request:
    branches: [main, stable]
  workflow_dispatch:

jobs:
  codecheck_job:
    uses: HyperPlay-Gaming/workflows/.github/workflows/nodejs_commands.yml@main
    with:
      node_version: '20'
      pkg_manager: 'pnpm'
      install: 'pnpm i'
      name: 'codecheck'
      command_one: 'pnpm codecheck'
      command_one_name: 'Codecheck'
      checkout_recursive: false
    secrets:
      NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'
