name: Lint and Prettier

on:
  pull_request:
    branches: [main, stable]
  workflow_dispatch:

jobs:
  release:
    uses: HyperPlay-Gaming/workflows/.github/workflows/nodejs_commands.yml@main
    with:
      node_version: '16'
      pkg_manager: 'yarn'
      install: 'yarn install --immutable --frozen-lockfile'
      name: 'lint'
      command_one: 'yarn lint'
      command_one_name: 'Lint code.'
      command_two: 'yarn prettier'
      command_two_name: 'Prettier code.'
      checkout_recursive: false
    secrets:
      NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'
