name: Release to npm

on:
  push:
    paths:
      - 'package.json'
    branches:
      - main

jobs:
  release:
    uses: HyperPlay-Gaming/workflows/.github/workflows/npm_publish.yml@main
    with:
      node_version: '16'
      pkg_manager: 'yarn'
      pkg_manager_add_dev_dep: 'yarn add -D'
      install: 'yarn install --immutable --frozen-lockfile'
      build: 'yarn build'
      publish: 'yarn publish'
    secrets:
      NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'
