name: 'Storybook Tests'

on:
  pull_request:
    branches: [main, stable]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright
        run: pnpm install playwright -g
      - name: setup playwright
        run: npx playwright@1.51.1 install --with-deps
      - name: Build Storybook
        run: pnpm build-storybook --quiet
      - name: Serve Storybook and run tests
        run: |
          pnpm add -g concurrently wait-on http-server
          pnpm concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "pnpm http-server storybook-static --port 6006 --silent" \
            "pnpm wait-on tcp:6006 && pnpm test-storybook"
