name: Unit Tests

on:
  pull_request:
    branches: [main, stable]
  workflow_dispatch:

jobs:
  unit_test:
    uses: HyperPlay-Gaming/workflows/.github/workflows/nodejs_commands.yml@main
    with:
      node_version: '22'
      pkg_manager: 'yarn'
      install: 'yarn install --immutable --frozen-lockfile'
      name: 'unit test'
      command_one: 'yarn test:unit'
      command_one_name: 'Run unit tests.'
      checkout_recursive: false
    secrets:
      NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'
